project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - slides/**/*.qmd
  resources:
    - activities/*.pdf
    - syllabus/*.pdf

website:
  title: "The AI Economy"
  site-url: "https://sjweymouth.github.io/course-ai-economy-slides/"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
